#!/bin/bash -xe

exec 2>&1

export CONSUL_UI_BETA={{cfg.server.beta_ui}}

exec consul agent \
  {{~#if cfg.server.ui}} -ui \{{/if}} 
  {{~#if cfg.server.dev}} -dev \{{/if}
  {{~#if cfg.server.mode}} -server -bootstrap-expect {{cfg.bootstrap.expect}} \{{/if}}
  {{#eachAlive bind.consul.members as |member|}}
    -retry-join {{member.sys.ip}} \
  {{~/eachAlive}}
  -config-file={{pkg.svc_config_path}}/basic_config.json
